# Generated by Django 5.1.1 on 2024-10-10 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folders',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='folders',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderlink',
            name='folderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.folders'),
        ),
        migrations.AddField(
            model_name='links',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderlink',
            name='linkID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.links'),
        ),
        migrations.AddField(
            model_name='linkstag',
            name='linkID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.links'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkstag',
            name='tagsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tags'),
        ),
    ]
