# Generated by Django 5.1.1 on 2024-10-13 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_category_userid_alter_folderlink_folderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dashboard.folders'),
        ),
    ]
