# Generated by Django 5.1.1 on 2024-10-19 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_links_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='folderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_tags', to='dashboard.folders'),
        ),
    ]
